BOARD=hk1mini
RELEASE=noble
BUILD_MINIMAL=no
BUILD_DESKTOP=no
CUSTOMIZE_IMAGE=yes
IMAGE_SIZE=1GB
KERNEL_TARGET=current
ENABLE_ROOT=true
ENABLE_E2FSCK=y
DISABLE_ROOT_RESIZE=false
CLEAN_LEVEL="make,debs"
