name: Build and Release RK322x Components

on:
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: armbian/build
        fetch-depth: 0
        
    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git bash bc bison flex libssl-dev make libc6-dev libncurses5-dev \
          crossbuild-essential-armhf debootstrap qemu-user-static device-tree-compiler \
          gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
        
    - name: Build U-Boot and Kernel
      run: |
        ./compile.sh BOARD=rk322x-box \
          BRANCH=current \
          RELEASE=jammy \
          BUILD_MINIMAL=yes \
          BUILD_DESKTOP=no \
          KERNEL_ONLY=yes \
          KERNEL_CONFIGURE=no \
          CLEAN_LEVEL="make,debs"
        
    - name: Collect artifacts
      run: |
        mkdir -p artifacts/rk322x
        # Copy U-Boot files
        cp output/debs/linux-u-boot-*rk322x-box*.deb artifacts/rk322x/
        cp output/debs/linux-dtb-*rk322x-box*.deb artifacts/rk322x/
        
        # Copy Kernel files
        cp output/debs/linux-headers-*.deb artifacts/rk322x/
        cp output/debs/linux-image-*.deb artifacts/rk322x/
        
        # Copy overlay files if available
        cp -r output/images/overlay-user/* artifacts/rk322x/ || echo "No overlay files found"
        
        # Create a simple README
        echo "RK322x Components from Armbian Build" > artifacts/README.md
        echo "Generated on $(date)" >> artifacts/README.md
        echo "" >> artifacts/README.md
        echo "Contains U-Boot, Kernel and Overlay files for RK322x devices." >> artifacts/README.md
        echo "Files:" >> artifacts/README.md
        ls -la artifacts/rk322x/ >> artifacts/README.md
        
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        name: RK322x Components $(date +'%Y-%m-%d')
        body: "Automated build of U-Boot, Kernel and Overlay for RK322x devices from Armbian build"
        tag_name: rk322x-$(date +'%Y%m%d')
        files: |
          artifacts/rk322x/*
          artifacts/README.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
