name: Build and Release RK322x Components

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC

jobs:
  build-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: armbian/build
        fetch-depth: 0
        
    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git bash bc bison flex libssl-dev make libc6-dev libncurses5-dev \
          crossbuild-essential-armhf debootstrap qemu-user-static device-tree-compiler \
          gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf \
          lsb-release
        
    - name: Build U-Boot and Kernel
      run: |
        # New command structure for Armbian
        ./compile.sh kernel BOARD=rk322x-box BRANCH=current \
          BUILD_MINIMAL=yes \
          BUILD_DESKTOP=no \
          KERNEL_CONFIGURE=no \
          CLEAN_LEVEL="make,debs"
        
    - name: Find and collect artifacts
      run: |
        mkdir -p artifacts/rk322x
        
        # Find and copy all relevant files with error handling
        echo "Searching for build artifacts..."
        
        # U-Boot files
        find output -name 'linux-u-boot-*rk322x-box*.deb' -exec cp {} artifacts/rk322x/ \; || echo "No U-Boot files found"
        find output -name 'linux-dtb-*rk322x-box*.deb' -exec cp {} artifacts/rk322x/ \; || echo "No DTB files found"
        
        # Kernel files
        find output -name 'linux-headers-*.deb' -exec cp {} artifacts/rk322x/ \; || echo "No headers found"
        find output -name 'linux-image-*.deb' -exec cp {} artifacts/rk322x/ \; || echo "No image found"
        
        # Overlay files
        find output -type d -name 'overlay-user' -exec cp -r {}/. artifacts/rk322x/ \; || echo "No overlay files found"
        
        # List collected files
        echo "Collected artifacts:"
        ls -la artifacts/rk322x/
        
        # Create a detailed README
        echo "# RK322x Components from Armbian Build" > artifacts/README.md
        echo "Generated on $(date)" >> artifacts/README.md
        echo "" >> artifacts/README.md
        echo "## Build Parameters" >> artifacts/README.md
        echo "- BOARD: rk322x-box" >> artifacts/README.md
        echo "- BRANCH: current" >> artifacts/README.md
        echo "- BUILD_MINIMAL: yes" >> artifacts/README.md
        echo "- KERNEL_CONFIGURE: no" >> artifacts/README.md
        echo "" >> artifacts/README.md
        echo "## Included Files" >> artifacts/README.md
        ls -1 artifacts/rk322x/ | sed 's/^/- /' >> artifacts/README.md
        
    - name: Create release
      if: success() && steps.collect.outcome == 'success'
      uses: softprops/action-gh-release@v1
      with:
        name: RK322x Components $(date +'%Y-%m-%d')
        body: "Automated build of U-Boot, Kernel and Overlay for RK322x devices from Armbian build\n\n$(cat artifacts/README.md)"
        tag_name: rk322x-$(date +'%Y%m%d')
        files: |
          artifacts/rk322x/*
          artifacts/README.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
