name: Build and Release RK322x Components

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC

jobs:
  build-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: armbian/build
        fetch-depth: 0
        
    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git bash bc bison flex libssl-dev make libc6-dev libncurses5-dev \
          crossbuild-essential-armhf debootstrap qemu-user-static device-tree-compiler \
          gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf \
          lsb-release
        
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
        
    - name: Build U-Boot and Kernel
      run: |
        ./compile.sh kernel BOARD=rk322x-box BRANCH=current \
          BUILD_MINIMAL=yes \
          BUILD_DESKTOP=no \
          KERNEL_CONFIGURE=no \
          CLEAN_LEVEL="make,debs"
        
    - name: Find and collect artifacts
      id: collect
      run: |
        mkdir -p artifacts/rk322x
        
        echo "Searching for build artifacts..."
        
        # Find and copy all kernel packages
        find output -name 'linux-*-current-rockchip_*.deb' -exec cp -v {} artifacts/rk322x/ \;
        
        # Find and copy U-Boot packages
        find output -name 'linux-u-boot-*rk322x*.deb' -exec cp -v {} artifacts/rk322x/ \;
        
        # Find and copy DTB packages
        find output -name 'linux-dtb-*rk322x*.deb' -exec cp -v {} artifacts/rk322x/ \;
        
        # Find and copy hashed kernel package
        find output/packages-hashed -name 'kernel-rockchip-*.tar' -exec cp -v {} artifacts/rk322x/ \;
        
        # List collected files
        echo "Collected artifacts:"
        ls -la artifacts/rk322x/
        
        # Create README with bykangris credit
        echo "# RK322x Components from Armbian Build" > artifacts/README.md
        echo "Generated on $(date)" >> artifacts/README.md
        echo "" >> artifacts/README.md
        echo "## Build Parameters" >> artifacts/README.md
        echo "- BOARD: rk322x-box" >> artifacts/README.md
        echo "- BRANCH: current" >> artifacts/README.md
        echo "- BUILD_MINIMAL: yes" >> artifacts/README.md
        echo "- KERNEL_CONFIGURE: no" >> artifacts/README.md
        echo "" >> artifacts/README.md
        echo "## Credits" >> artifacts/README.md
        echo "- Build automation by bykangris" >> artifacts/README.md
        echo "" >> artifacts/README.md
        echo "## Included Files" >> artifacts/README.md
        ls -1 artifacts/rk322x/ | sed 's/^/- /' >> artifacts/README.md
        
        # Set output for release step
        echo "artifact_count=$(ls -1 artifacts/rk322x/ | wc -l)" >> $GITHUB_OUTPUT
        
    - name: Create release
      if: steps.collect.outputs.artifact_count > 0
      uses: softprops/action-gh-release@v1
      with:
        name: RK322x Components ${{ steps.date.outputs.date }} (by bykangris)
        body: |
          Automated build of RK322x components from Armbian
          
          ### Build Details
          - Board: rk322x-box
          - Branch: current
          - Date: ${{ steps.date.outputs.date }}
          
          ### Credits
          Build automation by [bykangris](https://github.com/bykangris)
          
          $(cat artifacts/README.md)
        tag_name: rk322x-${{ steps.date.outputs.date }}
        files: |
          artifacts/rk322x/*
          artifacts/README.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
