name: Build RK322x U-Boot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        repository: pitekkate/build-rk322x
        ref: main

    - name: Install Dependencies
      run: |
        apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get install -y \
          git make gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu \
          device-tree-compiler u-boot-tools python3 libssl-dev \
          swig python3-dev bison flex

    - name: Clone U-Boot with RK322x Support
      run: |
        git clone https://github.com/rockchip-linux/u-boot.git -b rk322x
        cd u-boot
        git checkout 7a8bc15  # Commit yang diketahui support RK322x

    - name: Clone RK Binaries
      run: git clone https://github.com/rockchip-linux/rkbin.git

    - name: Verify Defconfig
      run: |
        cd u-boot
        if [ ! -f "configs/rk322x_defconfig" ]; then
          echo "::error::rk322x_defconfig not found!"
          echo "Available defconfigs:"
          ls configs/ | grep rk
          exit 1
        fi

    - name: Build U-Boot
      working-directory: ./u-boot
      run: |
        make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- rk322x_defconfig
        make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- -j$(nproc)

    - name: Generate idbloader.img
      working-directory: ./u-boot
      run: |
        tools/mkimage -n rk322x -T rksd -d ../rkbin/bin/rk32/rk322x_ddr_333MHz_v1.10.bin:idbloader.img
        cat spl/u-boot-spl.bin >> idbloader.img

    - name: Prepare Artifacts
      run: |
        mkdir -p rk322x-uboot
        cp u-boot/idbloader.img u-boot/u-boot.itb rk322x-uboot/
        
        cat > rk322x-uboot/BUILD_INFO <<EOF
        U-Boot Source: rockchip-linux/u-boot (rk322x branch)
        RK Binaries: rockchip-linux/rkbin
        Build Date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
        Toolchain: arm-linux-gnueabihf
        EOF
        
        tar -czvf rk322x-uboot.tar.gz -C rk322x-uboot .

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rk322x-uboot
        path: rk322x-uboot.tar.gz
        retention-days: 5
